# Generated by Django 5.0.3 on 2024-10-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_rename_vehicleowner_vehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='owner_age',
            field=models.CharField(default=20, max_length=100),
            preserve_default=False,
        ),
    ]
