# Generated by Django 5.0.3 on 2024-11-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_rename_vehicleowner_vehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='owner_address',
            field=models.CharField(default='Not provided', max_length=250),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_age',
            field=models.CharField(default=22, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_cnic',
            field=models.CharField(default='Not provided', max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_depart',
            field=models.CharField(default='Not provided', max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='male', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_phone',
            field=models.CharField(default='Not provided', max_length=100),
        ),
    ]
